// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxyA2RpvLEKpquu1mz5u20JfNJtfJ_7o0',
    appId: '1:130042215262:web:2bedc2016d1823a2e36dcf',
    messagingSenderId: '130042215262',
    projectId: 'oaze-fd2aa',
    authDomain: 'oaze-fd2aa.firebaseapp.com',
    storageBucket: 'oaze-fd2aa.firebasestorage.app',
    measurementId: 'G-QEY4KJBVZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkSAi0thjUk2SrkGZfffSP85VnKTdVtd4',
    appId: '1:130042215262:android:d1a819a5dbe8b55ee36dcf',
    messagingSenderId: '130042215262',
    projectId: 'oaze-fd2aa',
    storageBucket: 'oaze-fd2aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtcW45K3ZKY8ofZTGVWwHcFJfxcTcNfO8',
    appId: '1:130042215262:ios:0864eb6df3688408e36dcf',
    messagingSenderId: '130042215262',
    projectId: 'oaze-fd2aa',
    storageBucket: 'oaze-fd2aa.firebasestorage.app',
    iosClientId: '130042215262-suc7sst93qd67jp4588tngbupr14pjlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.oaze2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtcW45K3ZKY8ofZTGVWwHcFJfxcTcNfO8',
    appId: '1:130042215262:ios:0864eb6df3688408e36dcf',
    messagingSenderId: '130042215262',
    projectId: 'oaze-fd2aa',
    storageBucket: 'oaze-fd2aa.firebasestorage.app',
    iosClientId: '130042215262-suc7sst93qd67jp4588tngbupr14pjlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.oaze2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxyA2RpvLEKpquu1mz5u20JfNJtfJ_7o0',
    appId: '1:130042215262:web:ae40de8ee92efe1fe36dcf',
    messagingSenderId: '130042215262',
    projectId: 'oaze-fd2aa',
    authDomain: 'oaze-fd2aa.firebaseapp.com',
    storageBucket: 'oaze-fd2aa.firebasestorage.app',
    measurementId: 'G-2PYSPWQB0W',
  );
}
